name: conduit-deployer

ethereum:
  default_network: local
  local:
    default_provider: hardhat
  mainnet:
    transaction_acceptance_timeout: 600 # 10 minutes

polygon:
  mainnet:
    transaction_acceptance_timeout: 600 # 10 minutes

hardhat:
  request_timeout: 20 # Defaults to 30
  fork_request_timeout: 600 # Defaults to 300
  fork:
    ethereum:
      mainnet:
        upstream_provider: alchemy
      polygon:
        upstream_provider: alchemy
